# Generated by Django 5.1.5 on 2025-01-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_donor_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
    ]
