# Generated by Django 5.1.5 on 2025-03-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_donor_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
