# Generated by Django 5.1.5 on 2025-01-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_donationhistory_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationhistory',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
